api để gọi  author , genre , role ,  , chapter 
http://localhost/doanphp/Back-end/api/story.php
tương tự cho  các api khác  


ngoại lệ auth
http://localhost/doanphp/Back-end/api/auth.php?action=login
http://localhost/doanphp/Back-end/api/auth.php?action=register
http://localhost/doanphp/Back-end/api/auth.php?action=profile&user_id=  ở đây điền id 
000
quoc huy
đã phân quyền các file tacgia chuong the loai va truyen
tac gia chi co the chinh sua truyen cua minh con admin thi all